app:
  title: "Crawl4AI Server"
  version: "0.6.0"
  host: "0.0.0.0"
  port: 11235
  reload: false
  timeout_keep_alive: 300

llm:
  provider: "openai/gpt-4.1-nano"
  api_key_env: "OPENAI_API_KEY"

redis:
  host: "crawl4ai_redis"
  port: 6379
  db: 0
  password: ""

rate_limiting:
  enabled: true
  default_limit: "1000/minute"
  trusted_proxies: []
  storage_uri: "redis://crawl4ai_redis:6379/0"

security:
  enabled: false
  jwt_enabled: false
  https_redirect: false
  trusted_hosts: ["*"]
  headers:
    x_content_type_options: "nosniff"
    x_frame_options: "DENY"
    content_security_policy: "default-src 'self'"
    strict_transport_security: "max-age=63072000; includeSubDomains"

crawler:
  browser:
    headless: true
    extra_args: []
  pool:
    max_pages: 30
  memory_threshold_percent: 95.0

  rate_limiter:
    enabled: true
    base_delay: [1.0, 2.0]

  timeouts:
    stream_init: 30.0
    batch_process: 300.0

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

observability:
  prometheus:
    enabled: true
    endpoint: "/metrics"
  health_check:
    endpoint: "/health"
